name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LHCI_NO_LIGHTHOUSERC: 1
      LHCI_CHROME_FLAGS: "--no-sandbox --headless --disable-gpu"

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Clear npm cache
      run: npm cache clean --force
    - name: Install dependencies
      run: npm ci

    - name: Print npm log
      if: failure()
      run: cat /home/runner/.npm/_logs/*-debug.log

    - name: Install Lighthouse CI
      run: npm install -g @lhci/cli@0.8.x

    - name: Run Lighthouse CI
      run: lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"